steps:
- id: Execute Platform Provision using Terraform to provision GKE 
  name: 'hashicorp/terraform:latest'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      terraform -chdir="./platform/" init -no-color
      terraform -chdir="./platform/" apply -auto-approve -no-color
- id: Update authorised networks for private cluster to allow workload deployment
  name: gcr.io/cloudshell-images/cloudshell:latest
  args:
    - '-c'
    - |
        export SHELL_IP=$$(curl https://ipinfo.io/ip) && \
        echo $$SHELL_IP && \

        export CLUSTERNAME=$$(cat ./platform/platform.auto.tfvars | grep -w cluster_name | awk {'print $$NF'}| awk -F'["]' '{ print $$2 }')
        export REGION=$$(cat ./platform/platform.auto.tfvars | grep -w cluster_region | awk {'print $$NF'}| awk -F'["]' '{ print $$2 }')
        export PROJECT=$$(cat ./platform/platform.auto.tfvars | grep -w project_id | awk {'print $$NF'} | awk -F'["]' '{ print $$2 }')
        export ISPRIVATE=$$(gcloud container clusters describe  $$CLUSTERNAME --region $$REGION --format "value(privateClusterConfig.enablePrivateEndpoint)")

        if [[ $$ISPRIVATE == "False" ]]
        then 
          echo "WIP step, need to think more on this!!"
        else
          echo "GKE have private endpoint, consider enabling connect gateway!"
        fi 
  entrypoint: bash
- id: Deploy Workloads on provided platform GKE
  name: gcr.io/cloudshell-images/cloudshell:latest
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      apt-get install google-cloud-sdk-gke-gcloud-auth-plugin -y
      terraform -chdir="./workloads/" init -no-color
      terraform -chdir="./workloads/" apply -auto-approve -no-color 
serviceAccount: 'projects/$PROJECT_ID/serviceAccounts/aiongke@$PROJECT_ID.iam.gserviceaccount.com'
options:
  logging: CLOUD_LOGGING_ONLY